[phases.setup]
nixPkgs = ["ffmpeg", "python311Full"]

[phases.install]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "python main.py"
